// Spot Pack schema + validation + normalization.
//
// A Spot Pack describes a real (or fictional) fishing location the engine can
// play: an optional ASCII map, a species table with real behavior, tackle, and
// strategy notes. Generated by the `/nethook:spot` command (Claude) or hand-
// written. The engine NEVER trusts a pack blindly — validatePack() rejects
// malformed packs so a bad generation can't crash the game.

import { readFileSync, readdirSync, existsSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { RARITY } from "./fish.mjs";

const VALID_HABITATS = new Set(["shallow", "deep", "reeds", "any"]);
const VALID_RARITIES = new Set(Object.keys(RARITY));
const VALID_TIMES = new Set(["dawn", "day", "dusk", "night"]);
const VALID_SEASONS = new Set(["spring", "summer", "autumn", "winter"]);
const VALID_WEATHER = new Set(["clear", "cloudy", "rain", "fog", "wind", "storm", "snow"]);

// Normalize an optional gate field to a clean token list (or undefined =
// unrestricted). Tolerant by design: unknown tokens are dropped, "any" clears
// the gate, synonyms are folded — a sloppy pack degrades to "always available"
// rather than being rejected. (We still hard-reject bad core fields below.)
function normGate(v, valid, alias = {}) {
  if (v == null) return undefined;
  const arr = Array.isArray(v) ? v : [v];
  const out = [];
  for (const x of arr) {
    let t = String(x).toLowerCase().trim();
    if (alias[t]) t = alias[t];
    if (t === "any") return undefined;
    if (valid.has(t) && !out.includes(t)) out.push(t);
  }
  return out.length ? out : undefined;
}

export function slug(s) {
  return String(s).toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "") || "x";
}

function isNum(n) {
  return typeof n === "number" && Number.isFinite(n);
}

// Returns { ok, errors:[], pack } — `pack` is the normalized form when ok.
export function validatePack(raw) {
  const errors = [];
  if (typeof raw !== "object" || raw === null) {
    return { ok: false, errors: ["pack must be a JSON object"], pack: null };
  }
  if (typeof raw.name !== "string" || !raw.name.trim()) errors.push("name (string) required");
  if (!Array.isArray(raw.species) || raw.species.length === 0) {
    errors.push("species[] (non-empty) required");
  }

  const species = [];
  if (Array.isArray(raw.species)) {
    raw.species.forEach((sp, i) => {
      const where = `species[${i}]`;
      if (typeof sp !== "object" || sp === null) return errors.push(`${where} must be an object`);
      if (typeof sp.name !== "string" || !sp.name.trim()) errors.push(`${where}.name required`);
      const rarity = VALID_RARITIES.has(sp.rarity) ? sp.rarity : null;
      if (!rarity) errors.push(`${where}.rarity must be one of ${[...VALID_RARITIES].join("|")}`);
      const habitat = VALID_HABITATS.has(sp.habitat) ? sp.habitat : "any";
      const wr = sp.weightRange;
      if (!Array.isArray(wr) || wr.length !== 2 || !isNum(wr[0]) || !isNum(wr[1]) || wr[0] > wr[1]) {
        errors.push(`${where}.weightRange must be [min,max] numbers with min<=max`);
      }
      if (sp.glyph != null && (typeof sp.glyph !== "string" || [...sp.glyph].length !== 1)) {
        errors.push(`${where}.glyph must be a single character`);
      }
      if (rarity && Array.isArray(wr) && wr.length === 2 && isNum(wr[0]) && isNum(wr[1])) {
        species.push({
          id: slug(sp.name) + (sp.id ? "" : ""),
          name: sp.name.trim().slice(0, 40),
          glyph: sp.glyph || defaultGlyph(rarity),
          rarity,
          habitat,
          weightRange: [wr[0], wr[1]],
          strength: isNum(sp.strength) ? clamp(sp.strength, 1, 14) : strengthForRarity(rarity),
          behavior: typeof sp.behavior === "string" ? sp.behavior.slice(0, 200) : "",
          realInfo: typeof sp.realInfo === "string" ? sp.realInfo.slice(0, 200) : "",
          junk: !!sp.junk,
          // Optional environment gates (RESEARCH.md §4.6) — sanitized, never trusted.
          time: normGate(sp.time, VALID_TIMES),
          season: normGate(sp.season, VALID_SEASONS, { fall: "autumn" }),
          weather: normGate(sp.weather, VALID_WEATHER),
          bait: Array.isArray(sp.bait)
            ? sp.bait.map((x) => String(x).toLowerCase().trim()).filter(Boolean).slice(0, 6)
            : typeof sp.bait === "string"
              ? [sp.bait.toLowerCase().trim()]
              : undefined,
        });
      }
    });
  }

  // Optional map.
  let map = null;
  if (raw.map != null) {
    if (typeof raw.map !== "object" || !Array.isArray(raw.map.grid)) {
      errors.push("map.grid must be an array of strings when map is present");
    } else if (!raw.map.grid.every((row) => typeof row === "string")) {
      errors.push("map.grid rows must all be strings");
    } else {
      const w = Math.max(...raw.map.grid.map((r) => r.length));
      map = { grid: raw.map.grid, legend: raw.map.legend || {}, width: w, height: raw.map.grid.length };
    }
  }

  if (errors.length) return { ok: false, errors, pack: null };

  return {
    ok: true,
    errors: [],
    pack: {
      name: raw.name.trim().slice(0, 60),
      location: typeof raw.location === "string" ? raw.location.slice(0, 120) : "",
      notes: typeof raw.notes === "string" ? raw.notes.slice(0, 400) : "",
      map,
      species,
      tackle: Array.isArray(raw.tackle) ? raw.tackle.slice(0, 12) : [],
      strategy: Array.isArray(raw.strategy) ? raw.strategy.filter((s) => typeof s === "string").slice(0, 8) : [],
      hints: typeof raw.hints === "object" && raw.hints ? raw.hints : {},
    },
  };
}

function clamp(n, lo, hi) {
  return Math.max(lo, Math.min(hi, n));
}
function strengthForRarity(r) {
  return { common: 1, uncommon: 3, rare: 5, legendary: 8, mythic: 12 }[r] ?? 2;
}
function defaultGlyph(r) {
  return { common: "f", uncommon: "F", rare: "C", legendary: "S", mythic: "W" }[r] ?? "f";
}

export function loadPackFromFile(path) {
  const raw = JSON.parse(readFileSync(path, "utf8"));
  return validatePack(raw);
}

function builtinPacksDir() {
  return join(dirname(fileURLToPath(import.meta.url)), "packs");
}

// Lists installed packs from the built-in dir and (optionally) a user packs dir.
export function listPacks(userDir) {
  const out = [];
  for (const dir of [builtinPacksDir(), userDir].filter(Boolean)) {
    if (!existsSync(dir)) continue;
    for (const f of readdirSync(dir)) {
      if (!f.endsWith(".json")) continue;
      try {
        const res = loadPackFromFile(join(dir, f));
        if (res.ok) out.push({ file: join(dir, f), name: res.pack.name, builtin: dir === builtinPacksDir() });
      } catch {
        /* skip unreadable/invalid pack files */
      }
    }
  }
  return out;
}

// Resolve a pack by name (case-insensitive) or file path. Returns pack or null.
export function resolvePack(nameOrPath, userDir) {
  if (nameOrPath && existsSync(nameOrPath) && nameOrPath.endsWith(".json")) {
    const res = loadPackFromFile(nameOrPath);
    return res.ok ? res.pack : null;
  }
  const match = listPacks(userDir).find(
    (p) => slug(p.name) === slug(nameOrPath || "") || p.name.toLowerCase() === String(nameOrPath || "").toLowerCase(),
  );
  if (!match) return null;
  const res = loadPackFromFile(match.file);
  return res.ok ? res.pack : null;
}
